FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=development

RUN npm ci

COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WS_URL

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

ENV NODE_ENV=production

RUN echo "API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}"
RUN echo "API_WS_URL=${NEXT_PUBLIC_WS_URL}"

RUN rm -rf .next
RUN npm run build


# =========================
# PRODUCTION
# =========================
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3044
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3044

CMD ["node", "server.js"]