FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install ALL dependencies including devDeps
ENV NODE_ENV=development
RUN npm install

# Copy project files
COPY . .

# Build Next.js app
RUN npm run build



# ---- RUNTIME IMAGE ----
FROM node:20-alpine AS runner

WORKDIR /app

# Copy only necessary output from builder
COPY --from=builder /app/.next .next
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/package.json .

# Use production env at runtime
ENV NODE_ENV=production

EXPOSE 3044
CMD ["npm", "start"]
