name: Build & Push Docker Images

on:
  push:
    branches:
      - complete-prod

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------
      # CHECKOUT
      # --------------------------------------------------

      - name: Checkout
        uses: actions/checkout@v4

      # --------------------------------------------------
      # DOCKER HUB LOGIN
      # --------------------------------------------------

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: guru874
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # --------------------------------------------------
      # BACKEND
      # --------------------------------------------------

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./rise-bet-backend
          file: ./rise-bet-backend/Dockerfile
          push: true
          tags: |
            guru874/risebet-backend:latest
            guru874/risebet-backend:${{ github.sha }}

      # --------------------------------------------------
      # FRONTEND
      # --------------------------------------------------

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./DOCKERFILE
          push: true
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_WS_URL=${{ vars.NEXT_PUBLIC_WS_URL }}
          tags: |
            guru874/risebet-frontend:latest
            guru874/risebet-frontend:${{ github.sha }}

      # --------------------------------------------------
      # ADMIN
      # --------------------------------------------------

      - name: Build & Push Admin
        uses: docker/build-push-action@v6
        with:
          context: ./admin
          file: ./admin/Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_WS_URL=${{ vars.NEXT_PUBLIC_WS_URL }}
          tags: |
            guru874/risebet-admin:latest
            guru874/risebet-admin:${{ github.sha }}
